---
abstract: 'interface to open3 under AnyEvent'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Open3-Simple
requires:
  AnyEvent: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/AnyEvent-Open3-Simple/issues
  homepage: http://search.cpan.org/dist/AnyEvent-Open3-Simple/
  repository: git://github.com/plicease/AnyEvent-Open3-Simple.git
version: 0.63
