---
abstract: 'interface to open3 under AnyEvent'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 1
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-Open3-Simple
recommends:
  EV: '0'
requires:
  AnyEvent: '0'
  perl: '5.008'
  warnings::register: '0'
resources:
  bugtracker: https://github.com/plicease/anyevent-open3-simple/issues
  homepage: http://perl.wdlabs.com/AnyEvent-Open3-Simple/
  repository: git://github.com/plicease/anyevent-open3-simple.git
version: '0.77'
