---
abstract: 'interface to open3 under AnyEvent'
author:
  - 'Graham Ollis <plicease@wdlabs.com>'
build_requires:
  Exporter: 0
  File::Spec: 0
  File::Temp: 0
  Test::More: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Open3-Simple
requires:
  AnyEvent: 0
  IPC::Open3: 0
  Symbol: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/plicease/AnyEvent-Open3-Simple/issues
  homepage: http://search.cpan.org/dist/AnyEvent-Open3-Simple/
  repository: git://github.com/plicease/AnyEvent-Open3-Simple.git
version: 0.3
